// quotes.js
const TURKISH_QUOTES = [
  { q: "Boşver, dünya dönüyor!", a: "Anonim" },
  { q: "Gerisi zaten boşverilecek kadar önemsiz.", a: "Anonim" },
  { q: "Boşversene, yeter ki içinden geleni yap.", a: "Anonim" },
  { q: "Muti’yi unutma, o senin yol yoldaşın.", a: "İç ses" },
  { q: "Muti gibi parla, ama asla sönen yıldız olma.", a: "Anonim" },
  { q: "Her sabah uyanmak, hayata bir şans daha demektir.", a: "Anonim" },
  { q: "Hayat kısa, gülümsemeden geçme.", a: "Anonim" },
  { q: "Yaşamak, bir sanattır. Her nefes bir fırça darbesidir.", a: "Anonim" },
  { q: "Aşk, paylaştıkça çoğalan tek şeydir.", a: "Anonim" },
  { q: "Gözlerinle değil, yüreğinle sev.", a: "Anonim" },
  { q: "Düşünceyi değiştir, hayatı değiştir.", a: "Marcus Aurelius" },
  { q: "Bilgi güçtür.", a: "Francis Bacon" },
  { q: "Ben düşündüğüm için varım.", a: "Descartes" },
  { q: "Güzellik, gözle değil, yürekle görülür.", a: "Türk atasözü" },
  { q: "Güzel şeyler, sabırla bekleyenlere gelir.", a: "Türk atasözü" },
  { q: "Dost, kara günde belli olur.", a: "Türk atasözü" },
  { q: "Hayal kurmaktan korkma, çünkü hayaller gerçek olur.", a: "Walt Disney" },
  { q: "Başarı, hedeflerin peşinden koşmaktır.", a: "Zig Ziglar" },
  { q: "Yarın diye bir şey yok, sadece bugün var.", a: "Anonim" },
  { q: "Rüzgâr ol, fırtına ol, ama asla susma.", a: "Anonim" },
  { q: "Ay ışığı gibi sessizce parla.", a: "Anonim" },
  { q: "Sen kendin ol, çünkü başkası zaten var.", a: "Anonim" },
  { q: "Gülümse, çünkü gülümsemek bedava ama etkisi pahalı.", a: "Anonim" },
  { q: "Zaman her şifayı verir, sabret.", a: "Anonim" },
  { q: "Sessizlik bazen en güçlü cevaptır.", a: "Anonim" },
  { q: "Kendine güven; gerisi zaten boşverilecek kadar önemsiz.", a: "Anonim" },
  { q: "Unutma: sen bir mucizesin.", a: "Anonim" },
  { q: "Kalbini dinle, o hep doğruyu fısıldar.", a: "Anonim" },
  { q: "Her gece biter, her sabah doğar.", a: "Anonim" },
  { q: "İyi ki varsın diyebildiğin insanlar, hayatı değerli kılar.", a: "Anonim" },
  { q: "Korku, hayal gücünün başka bir adıdır.", a: "Anonim" },
  { q: "Sen bir yıldızsın, sönme!", a: "Anonim" },
  { q: "Yolun açık olsun, yüreğin hep aydın.", a: "Anonim" },
  { q: "Yıldızlara dokunamazsın, ama onlar seni aydınlatır.", a: "Anonim" },
  { q: "Gözlerin hep aydınlık olsun.", a: "Anonim" },
  { q: "Bazen susmak, en büyük cevaptır.", a: "Anonim" },
  { q: "Kendine iyi bak, çünkü sen eşsizsin.", a: "Anonim" },
  { q: "Hayat bir yolculuktur, varış değil.", a: "Anonim" },
  { q: "Gülüşün bulaşıcı olsun.", a: "Anonim" },
  { q: "İçindeki ışığı saklama.", a: "Anonim" },
  { q: "Zorluklar, seni şekillendirir.", a: "Anonim" },
  { q: "Bugün, yarının temelidir.", a: "Anonim" },
  { q: "Her şeyin bir zamanı vardır.", a: "Anonim" },
  { q: "Dünya senden çok şey bekliyor.", a: "Anonim" },
  { q: "Bir adım geri atmak, iki adım ileri gitmektir.", a: "Anonim" },
  { q: "Güneş her sabah doğar, sen de öyle yap.", a: "Anonim" },
  { q: "Kendin olmak cesaret ister.", a: "Anonim" },
  { q: "Hayat senden ne istediğini sorduğunda: 'Parla' de.", a: "Anonim" },
  { q: "Gecenin karanlığı, sabahın güzelliğini anlatır.", a: "Anonim" },
  { q: "Her şey bir anlam taşır, inan.", a: "Anonim" },
  { q: "Dünyayı değiştiremezsin, ama kendini değiştirebilirsin.", a: "Anonim" },
  { q: "Sessizce güçlü ol.", a: "Anonim" },
  { q: "İçindeki ateşi asla söndürme.", a: "Anonim" },
  { q: "Güven, zamanla inşa edilir.", a: "Anonim" },
  { q: "Yol uzun, ama sen daha uzun.", a: "Anonim" },
  { q: "Gözlerin hep hedefte olsun.", a: "Anonim" },
  { q: "Kalbini kırmasınlar, sen onu koru.", a: "Anonim" },
  { q: "Her şeye rağmen umut.", a: "Anonim" },
  { q: "Sadece sen, sen olabilirsin.", a: "Anonim" },
  { q: "Hayat, küçük anların birleşimidir.", a: "Anonim" },
  { q: "Gülümsemen, bir başkasının güneşi olabilir.", a: "Anonim" },
  { q: "Düşlerin seni bulsun.", a: "Anonim" },
  { q: "Asla pes etme, çünkü son adım her zaman en zoru.", a: "Anonim" },
  { q: "İyi insan olmak, en büyük başarıdır.", a: "Anonim" },
  { q: "Her şey bir gün yerine oturacak.", a: "Anonim" },
  { q: "Senden başka kimse senin yolunu çizemez.", a: "Anonim" },
  { q: "Gönül ne isterse, onu yap.", a: "Yunus Emre" },
  { q: "Aşk, her şeyi affeder.", a: "Anonim" },
  { q: "Sabır acıdır, ama meyvesi tatlıdır.", a: "Anonim" },
  { q: "Sevgiyle yapılan her şey kalıcıdır.", a: "Anonim" },
  { q: "Dost, can yoldaşıdır.", a: "Anonim" },
  { q: "İnsanı insan yapan, merhametidir.", a: "Anonim" },
  { q: "Doğruyu söylemek cesaret ister.", a: "Anonim" },
  { q: "Barış, en büyük zaferdir.", a: "Anonim" },
  { q: "Yalnızlık, kendini tanımaya fırsat verir.", a: "Anonim" },
  { q: "Gözlerin hep gökyüzünde olsun.", a: "Anonim" },
  { q: "Hayat, bir gülüşle güzelleşir.", a: "Anonim" },
  { q: "Kendine iyi davran, çünkü senden başka kimse seni tam olarak bilmez.", a: "Anonim" },
  { q: "Her sabah yeni bir başlangıçtır.", a: "Anonim" },
  { q: "Gözlerin hep ileriye bakmalı.", a: "Anonim" },
  { q: "İçindeki çocuk asla ölmesin.", a: "Anonim" },
  { q: "Daima umutla yürü.", a: "Anonim" },
  { q: "Hayat, denge oyunudur.", a: "Anonim" },
  { q: "Güzel kalpli olmak, en büyük zenginliktir.", a: "Anonim" },
  { q: "Her şey bir sebepten olur.", a: "Anonim" },
  { q: "Yüreğin hep sıcak kalsın.", a: "Anonim" },
  { q: "Hayat, bir dans gibidir.", a: "Anonim" },
  { q: "Gözlerin hep yıldızlara bakmalı.", a: "Anonim" },
  { q: "Kendini sevmeden başkasını sevemezsin.", a: "Anonim" },
  { q: "Her gün yeni bir fırsat.", a: "Anonim" },
  { q: "Gönül huzuru her şeyden kıymetlidir.", a: "Anonim" },
  { q: "İçindeki sesi dinle.", a: "Anonim" },
  { q: "Hayat, küçük mutluluklardan oluşur.", a: "Anonim" },
  { q: "Gözlerin hep güneşe bakmalı.", a: "Anonim" },
  { q: "Her şey geçer, sabret.", a: "Anonim" },
  { q: "Kendine inan, çünkü sen yeterince güçlüsün.", a: "Anonim" },
  { q: "Hayat, bir yolculuktur.", a: "Anonim" },
  { q: "Güzel düş, güzel yaşa.", a: "Anonim" },
  { q: "Her sabah yeni bir umut doğar.", a: "Anonim" },
  { q: "Kalbin hep temiz kalsın.", a: "Anonim" },
  { q: "Hayat, bir fırsattır.", a: "Anonim" },
  { q: "Gözlerin hep denizlere bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün anlam kazanacak.", a: "Anonim" },
  { q: "Kendini ifade etmek cesaret ister.", a: "Anonim" },
  { q: "Hayat, bir armağandır.", a: "Anonim" },
  { q: "Gözlerin hep dağlara bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün güzelleşecek.", a: "Anonim" },
  { q: "Kendine zaman ayır.", a: "Anonim" },
  { q: "Hayat, bir şarkıdır.", a: "Anonim" },
  { q: "Gözlerin hep ormana bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün yoluna girecek.", a: "Anonim" },
  { q: "Kendini affet.", a: "Anonim" },
  { q: "Hayat, bir resim gibidir.", a: "Anonim" },
  { q: "Gözlerin hep bulutlara bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün açıklığa kavuşacak.", a: "Anonim" },
  { q: "Kendine değer ver.", a: "Anonim" },
  { q: "Hayat, bir şiir gibidir.", a: "Anonim" },
  { q: "Gözlerin hep yağmura bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün yerli yerine oturacak.", a: "Anonim" },
  { q: "Kendine iyi bak.", a: "Anonim" },
  { q: "Hayat, bir hediye gibidir.", a: "Anonim" },
  { q: "Gözlerin hep karlara bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün güzel görünecek.", a: "Anonim" },
  { q: "Kendine güven.", a: "Anonim" },
  { q: "Hayat, bir mucizedir.", a: "Anonim" },
  { q: "Gözlerin hep çiçeklere bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün anlam kazanacak.", a: "Anonim" },
  { q: "Kendine zaman tanı.", a: "Anonim" },
  { q: "Hayat, bir fırsat gibidir.", a: "Anonim" },
  { q: "Gözlerin hep yere bakma, yukarı bak.", a: "Anonim" },
  { q: "Her şey bir gün güzelleşecek.", a: "Anonim" },
  { q: "Kendine iyi davran.", a: "Anonim" },
  { q: "Hayat, bir hediye.", a: "Anonim" },
  { q: "Gözlerin hep ufkak bakmalı.", a: "Anonim" },
  { q: "Her şey bir gün yoluna girecek.", a: "Anonim" },
  { q: "Kendine değer kat.", a: "Anonim" },
  { q: "Hayat, bir dans.", a: "Anonim" },
  { q: "Gözlerin hep güneşe bak.", a: "Anonim" },
  { q: "Her şey bir gün açıklığa kavuşacak.", a: "Anonim" },
  { q: "Kendine iyi bak, çünkü sen eşsizsin.", a: "Anonim" }
];
